---
title: "Group reference"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Group reference}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    message = FALSE,
    warning = FALSE,
    collapse = TRUE,
    comment = "#>",
    dpi = 150
)
```

Use this as a very ugly reference for availability of categories and groups by year. Partly this is so we have a git-trackable list.

```{r}
library(dcws)
library(dplyr)
library(tidyr)
```

```{r results='asis'}
grps <- cws_full_data %>%
    unnest(survey) %>%
    unnest(data) %>%
    distinct(name, year, category, group) %>%
    filter(category != "Total", !group %in% stringr::str_to_title(cwi::ct5_clusters$cluster)) %>%
    mutate(value = "x")

grps %>%
    split(.$category, drop = TRUE) %>%
    purrr::map(pivot_wider, id_cols = c(name), names_from = group, values_from = year, values_fn = list(year = toString), names_sort = TRUE, values_fill = "") %>%
    purrr::map(arrange, name) %>%
    purrr::iwalk(function(df, category) {
        cat(paste("##", category))
        print(knitr::kable(df))
    })
```



